{
 "title": "RH System",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{id=\"PS Old Gen\"}",
     "legendFormat": "Max Memory"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"PS Old Gen\"}",
     "legendFormat": "Committed Memory"
    },
    {
     "expr": "jvm_memory_used_bytes{id=\"PS Old Gen\"}",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tomcat_threads_busy_threads", "legendFormat": "Busy" },
    { "expr": "tomcat_threads_current_threads", "legendFormat": "Current" },
    {
     "expr": "tomcat_threads_config_max_threads",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "State" }
   ]
  },
  {
   "title": "Requests",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[5m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Kafka Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_records_consumed_total_records_total[5m])",
     "legendFormat": "topic-{{topic}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "CPU Usage" }
   ]
  }
 ]
}