global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'RH Server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8090']