apiVersion: v1
kind: Pod
metadata:
  name: kafka
  namespace: rh
  labels:
    app: kafka
spec:
  containers:
    - name: kafka
      image: wurstmeister/kafka
      env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 10.96.143.114
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service.rh.svc.cluster.local:2181
        - name: KAFKA_BROKER_ID
          value: "1"
      ports:
        - name: kafka
          containerPort: 9092
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: rh  
spec:
  selector:
    app: kafka
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092